services:
  - type: web
    name: gumtree-clone-web
    env: ruby
    plan: free
    numInstances: 1
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/deploy/puma.rb
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
    #   - key: DATABASE_URL
    #     fromDatabase:
    #       name: gumtree-clone-db
    #       property: connectionString
          
# databases:
#   - name: gumtree-clone-db
#     plan: free
#     postgresMajorVersion: 14
